### ISSUE TITLE
estimate-shipping-methods  500 error code

### ISSUE THREAD

**Issue by beautycos** [wexo/module-instabox#1]
When there is an error in Wexo\Instabox\Model\Api->authenticate() the estimate-shipping-methods in checkout gives a 500.

So instead of showing no shipping methods just skip this method (for a potential solution see diff).

diff vendor/wexo/module-instabox/Model/Carrier:

> 
> 149,155c149
> \<             try {
> \<                 $parcelShopTitle = $this->instaboxApi->getFirstParcelShopName();
> \<             } catch (\Throwable $th) {
> \<                 $parcelShopTitle = null;
> \<                 // TODO log error
> \<             }
> \< 
> \---
> \>             $parcelShopTitle = $this->instaboxApi->getFirstParcelShopName();
> 157c151
> \<             if ($showAsOption && isset($parcelShopTitle)) {
> \---
> \>             if ($showAsOption) {
> 

Exception trace:
#0 /vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create()
#1 /vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}()
#2 /vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler()
#3 /vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Promise\TaskQueue->run()
#5 /vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn()
#6 /vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
#7 /vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList()
#8 /vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#9 /vendor/guzzlehttp/guzzle/src/Client.php(182): GuzzleHttp\Promise\Promise->wait()
#10 /vendor/guzzlehttp/guzzle/src/Client.php(95): GuzzleHttp\Client->request()
#11 /vendor/wexo/module-instabox/Model/Api.php(290): GuzzleHttp\Client->__call()
#12 /vendor/wexo/module-instabox/Model/Api.php(583): Wexo\Instabox\Model\Api->authenticate()
#13 /vendor/wexo/module-instabox/Model/Api.php(315): Wexo\Instabox\Model\Api->getClient()
#14 /vendor/wexo/module-instabox/Model/Api.php(161): Wexo\Instabox\Model\Api->request()
#15 /vendor/wexo/module-instabox/Model/Api.php(351): Wexo\Instabox\Model\Api->getParcelShops()
#16 /vendor/wexo/module-instabox/Model/Carrier/Instabox.php(149): Wexo\Instabox\Model\Api->getFirstParcelShopName()
#17 /vendor/magento/module-shipping/Model/Shipping.php(337): Wexo\Instabox\Model\Carrier\Instabox->collectRates()
#18 /vendor/magento/module-shipping/Model/Shipping.php(244): Magento\Shipping\Model\Shipping->collectCarrierRates()
#19 /vendor/magento/module-quote/Model/Quote/Address.php(1076): Magento\Shipping\Model\Shipping->collectRates()
#20 /generated/code/Magento/Quote/Model/Quote/Address/Interceptor.php(239): Magento\Quote\Model\Quote\Address->requestShippingRates()
#21 /vendor/magento/module-quote/Model/Quote/Address.php(1003): Magento\Quote\Model\Quote\Address\Interceptor->requestShippingRates()
#22 /generated/code/Magento/Quote/Model/Quote/Address/Interceptor.php(230): Magento\Quote\Model\Quote\Address->collectShippingRates()
#23 /vendor/magento/module-quote/Model/Quote/Address/Total/Shipping.php(84): Magento\Quote\Model\Quote\Address\Interceptor->collectShippingRates()
#24 /vendor/magento/module-quote/Model/Quote/TotalsCollector.php(274): Magento\Quote\Model\Quote\Address\Total\Shipping->collect()
#25 /generated/code/Magento/Quote/Model/Quote/TotalsCollector/Interceptor.php(41): Magento\Quote\Model\Quote\TotalsCollector->collectAddressTotals()
#26 /vendor/magento/module-quote/Model/ShippingMethodManagement.php(322): Magento\Quote\Model\Quote\TotalsCollector\Interceptor->collectAddressTotals()
#27 /vendor/magento/module-quote/Model/ShippingMethodManagement.php(258): Magento\Quote\Model\ShippingMethodManagement->getShippingMethods()
#28 /vendor/magento/module-quote/Model/GuestCart/GuestShippingMethodManagement.php(103): Magento\Quote\Model\ShippingMethodManagement->estimateByExtendedAddress()
#29 [internal function]: Magento\Quote\Model\GuestCart\GuestShippingMethodManagement->estimateByExtendedAddress()
#30 /vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array()
#31 /vendor/magento/module-webapi/Controller/Rest.php(188): Magento\Webapi\Controller\Rest\SynchronousRequestProcessor->process()
#32 /vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch()
#33 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent()
#34 /vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}()
#35 /generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(23): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins()
#36 /vendor/magento/framework/App/Http.php(116): Magento\Webapi\Controller\Rest\Interceptor->dispatch()
#37 /generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch()
#38 /vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http\Interceptor->launch()
#39 /pub/index.php(29): Magento\Framework\App\Bootstrap->run()
#40 {main}

**Comment by WebKenth** [comment]
I've updated the module to handle all exceptions thrown in the collect rates gracefully and it will simply log the errors instead of breaking checkout

https://github.com/wexo/module-instabox/commit/1f906c2364f11dc195161775f9719a611dce1f32

However Authentication should never return a HTTP status 500, either the authentication service is down, or you are supplying invalid credentials

You must fill out

- Client_id
- Client_secret
- Customer_number

otherwise the module cannot authenticate with Instabox Services :) 

@beautycos  to update the module just run: 

```
composer update wexo/module-instabox
```


Side note: the diff you supplied is invalid ;) 

Try running `diff -u <file1> <file2>` when showing differences made this produces a valid diff which can simply be applied using `git apply`

**Comment by beautycos** [comment]
It works, great job.


It was not the authentication that returned a 500. It was the rest api in Magento (estimate-shipping-methods from checkout page).
